### ISSUE TITLE
Create a Navbar in bootstrap 5 

### ISSUE THREAD

**Issue by NishikantaRay** [NishikantaRay/Losit#136]
step 1- fork the repo 
step 2 - npm i && npm start
step 3 - add your code inside the Frontend folder
step 4 - create a pull request for code review

It should look like the below image 

<img width="960" alt="image" src="https://user-images.githubusercontent.com/62615392/193846380-404eeec6-0a40-4606-87ed-5e979225c883.png">

**Comment by Eyesnatcher-coder** [comment]
Hello @NishikantaRay  , can you please assign the issue to me ?
