### ISSUE TITLE
Create a Footer using bootstrap5

### ISSUE THREAD

**Issue by NishikantaRay** [NishikantaRay/Losit#137]
step 1- fork the repo 
step 2 - npm i && npm start
step 3 - add your code inside the Frontend folder
step 4 - create a pull request for code review

It should look like the below image 
<img width="946" alt="image" src="https://user-images.githubusercontent.com/62615392/193848736-a4e670b0-bea1-43f2-91b7-e82d3c849252.png">

**Comment by andreaevolo** [comment]
I would like to be assigned to this issue 😄
