### ISSUE TITLE
Create a api for delete a listing card data

### ISSUE THREAD

**Issue by NishikantaRay** [NishikantaRay/Losit#151]
1-Name (string)
2-description (string)
3-IMG-URL (array of objects)
4-social media URL (Array of objects) should be in key-value pair

step 1- fork the repo
step 2 - npm i && npm start
step 3 - add your code inside the backend folder
step 4 - create a pull request for code review

**Comment by rajkumardongre** [comment]
Hello, I want to work on this issue, can you assign this to me, please

**Comment by rajkumardongre** [comment]
is this issue still open
